contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://chenshuiyin.github.io/"
canonifyurls = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "shuiyin"
  author = "chenshuiyin"
